version: '3.7'

services:

  web:
    image: bleskomat/bleskomat-server:latest
    container_name: bleskomat-server-web
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - web_datadir:/usr/src/app/data
    environment:
      DEBUG: "bleskomat*,lnurl*"
      BLESKOMAT_SERVER_HOST: "0.0.0.0"
      BLESKOMAT_SERVER_PORT: "3000"
      BLESKOMAT_SERVER_URL: "https://DOMAINNAME"
      BLESKOMAT_SERVER_ENDPOINT: "/u"
      BLESKOMAT_SERVER_AUTH_API_KEYS: '[]'
      BLESKOMAT_SERVER_LIGHTNING: '{"backend":"dummy","config":{}}'
      BLESKOMAT_SERVER_STORE: '{"backend":"knex","config":{"client":"sqlite3","connection":{"filename":"./data/db.sqlite3"},"useNullAsDefault":true}}'
      BLESKOMAT_SERVER_ADMIN_WEB: "true"
      BLESKOMAT_SERVER_ENV_FILEPATH: "./data/.env"

volumes:
  web_datadir:
