name: tests
on: [push, pull_request]
jobs:
  memory:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        env:
          BLESKOMAT_SERVER_HOST: localhost
          BLESKOMAT_SERVER_PORT: 3000
          BLESKOMAT_SERVER_URL: http://localhost:3000
          BLESKOMAT_SERVER_ENDPOINT: /u
          BLESKOMAT_SERVER_AUTH_API_KEYS: '[]'
          BLESKOMAT_SERVER_LIGHTNING: '{"backend":"dummy","config":{}}'
          BLESKOMAT_SERVER_STORE: '{"backend":"memory","config":{}}'
          BLESKOMAT_SERVER_COINRATES_DEFAULTS_PROVIDER: dummy
        run: npm test
