name: tests
on: [push, pull_request]
env:
  DB_USER: bleskomat_server_test
  DB_PASS: bleskomat_server_test
  DB_NAME: bleskomat_server_test
jobs:
  memory:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        env:
          DEBUG: bleskomat*,lnurl*
          BLESKOMAT_SERVER_HOST: localhost
          BLESKOMAT_SERVER_PORT: 3000
          BLESKOMAT_SERVER_URL: http://localhost:3000
          BLESKOMAT_SERVER_ENDPOINT: /u
          BLESKOMAT_SERVER_AUTH_API_KEYS: '[]'
          BLESKOMAT_SERVER_LIGHTNING: '{"backend":"dummy","config":{}}'
          BLESKOMAT_SERVER_STORE: '{"backend":"memory","config":{}}'
          BLESKOMAT_SERVER_COINRATES_DEFAULTS_PROVIDER: dummy
        run: npm test
  mysql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASS }}
          MYSQL_RANDOM_ROOT_PASSWORD: 1
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Install data store dependencies
        run: npm install knex@0.95.x mysql@2.18.x
      - name: Run Tests
        env:
          DEBUG: bleskomat*,lnurl*
          BLESKOMAT_SERVER_HOST: localhost
          BLESKOMAT_SERVER_PORT: 3000
          BLESKOMAT_SERVER_URL: http://localhost:3000
          BLESKOMAT_SERVER_ENDPOINT: /u
          BLESKOMAT_SERVER_AUTH_API_KEYS: '[]'
          BLESKOMAT_SERVER_LIGHTNING: '{"backend":"dummy","config":{}}'
          BLESKOMAT_SERVER_STORE: '{"backend":"knex","config":{"client":"mysql","connection":{"host":"localhost","port":"${{ job.services.mysql.ports[3306] }}","user":"${{ env.DB_USER }}","password":"${{ env.DB_PASS }}","database":"${{ env.DB_NAME }}"}}}'
          BLESKOMAT_SERVER_COINRATES_DEFAULTS_PROVIDER: dummy
        run: npm test
  postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    services:
      postgres:
        image: postgres:10
        ports:
          - 5432
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASS }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Install data store dependencies
        run: npm install knex@0.95.x pg@8.6.x
      - name: Run Tests
        env:
          DEBUG: bleskomat*,lnurl*
          BLESKOMAT_SERVER_HOST: localhost
          BLESKOMAT_SERVER_PORT: 3000
          BLESKOMAT_SERVER_URL: http://localhost:3000
          BLESKOMAT_SERVER_ENDPOINT: /u
          BLESKOMAT_SERVER_AUTH_API_KEYS: '[]'
          BLESKOMAT_SERVER_LIGHTNING: '{"backend":"dummy","config":{}}'
          BLESKOMAT_SERVER_STORE: '{"backend":"knex","config":{"client":"pg","connection":{"host":"localhost","port":"${{ job.services.postgres.ports[5432] }}","user":"${{ env.DB_USER }}","password":"${{ env.DB_PASS }}","database":"${{ env.DB_NAME }}"}}}'
          BLESKOMAT_SERVER_COINRATES_DEFAULTS_PROVIDER: dummy
        run: npm test
  sqlite3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Install data store dependencies
        run: npm install knex@0.95.x sqlite3@5.0.x
      - name: Run Tests
        env:
          DEBUG: bleskomat*,lnurl*
          BLESKOMAT_SERVER_HOST: localhost
          BLESKOMAT_SERVER_PORT: 3000
          BLESKOMAT_SERVER_URL: http://localhost:3000
          BLESKOMAT_SERVER_ENDPOINT: /u
          BLESKOMAT_SERVER_AUTH_API_KEYS: '[]'
          BLESKOMAT_SERVER_LIGHTNING: '{"backend":"dummy","config":{}}'
          BLESKOMAT_SERVER_STORE: '{"backend":"knex","config":{"client":"sqlite3","connection":{"filename":"./test.sqlite3"},"useNullAsDefault":true}}'
          BLESKOMAT_SERVER_COINRATES_DEFAULTS_PROVIDER: dummy
        run: npm test
